---
# Welcome to oreRewards V1.0.1 !

# Command /reward
description_command: "allows to see the total of its rewards withdrawn"

# UI /reward
Title_ui: "§6Plugin reward"
Content_ui: "§aYou have §6{rewards} to withdraw from your account"
Button_1_ui: "§4remove"
Button_2_ui: "§6let"

message_remove_rewards: "§a{amount} §6euros was added to your money"
message_not_reward: "§4You haven't got any reward !"

# 1 = 1$
# 1000 = 1000$
# USAGE: "ID:DAMAGE": AMOUNT
Rewards:
  "1:0": 1
  "16:0": 10
  "15:0": 50
  "14:0": 100
  "21:0": 150
  "56:0": 200
  "129:0": 500
...