---
# Welcome to oreRewards V1.0.0 !


# Command /reward
description_command: "allows to see the total of its rewards withdrawn"

# UI /reward
Title_ui: "§6Plugin reward"
Content_ui: "§aYou have §6{rewards} to withdraw from your account"
Button_1_ui: "§4remove"
Button_2_ui: "§6let"

message_remove_rewards: "§a{amount} §6euros was added to your money"
message_not_reward: "§4You have any reward !"

# 1 = 1$
# 1000 = 1000$
Stone: 1
Coal: 10
Iron_ore: 50
Gold_ore: 100
Lapis_ore: 150
Diamond_ore: 200
Emerald_ore: 500
...